### ISSUE TITLE
Criar modelo coredata.

### ISSUE THREAD

**Issue by WendelSilva** [WendelSilva/AppSid#2]
Criar modelo coredata.

**Comment by Viviane21** [comment]
1. Salvar nome;
2. Salvar opção escolhida (menino ou menina);
3. Salvar pontuação para o jogo da memória (letras);
4. Salvar pontuação para o jogo da memória (números);
5. Salvar pontuação para jogo da memória (outra opção escolhida) - futuramente;
6. Salvar pontuação para jogo da silhueta (letras) - próxima sprint; 
7. Salvar pontuação para jogo da silhueta (números) - próxima sprint;
8. Salvar pontuação para jogo da silhueta (outra opção escolhida) - futuramente;
